### ISSUE TITLE
Challenge 1 password

### ISSUE THREAD

**Issue by rendello** [tosrevive/TOSMiniCTF2020#1]
006ad7a0798c0e526f83256c64f4d0a0aa78d067d0e29851a414ce81715e27c4

**Comment by tosrevive** [comment]
Haha, are you testing my hacking skills to see if I can reverse a SHA 256 hash?  Indeed I know what you hashed and I can tell you that the password you used to make this hash is off by one character (the 4th character is wrong).

**Comment by rendello** [comment]
99e8c46183f3cdb67b4a43e2d814e465c4984bc1e5c6b78ed5e8a4f5aa4e0cdf

Whoops, muscle memory ;)

**Comment by tosrevive** [comment]
Correct answer!  I actually like your answer better, I should have made it that!
